ifeq ($(BCMSDK),)
$(error BCMSDK must be set to the root of the OpenNSA source tree)
endif

obj-m := bcm-kernel-bde.o
bcm-kernel-bde-y := linux-kernel-bde.o
bcm-kernel-bde-y += linux_dma.o
bcm-kernel-bde-y += linux_shbde.o
bcm-kernel-bde-y += ../shared/mpool.o
bcm-kernel-bde-y += ../../shared/shbde_iproc.o
bcm-kernel-bde-y += ../../shared/shbde_mdio.o
bcm-kernel-bde-y += ../../shared/shbde_pci.o
bcm-kernel-bde-y += ../../../linux/kernel/modules/shared/gmodule.o
ccflags-y := -I$(BCMSDK)/src/gpl-modules/systems/linux/kernel/modules/include/
ccflags-y += -I$(BCMSDK)/src/gpl-modules/systems/bde/linux/include/
ccflags-y += -I$(BCMSDK)/src/gpl-modules/systems/bde/shared/include/
ccflags-y += -I$(BCMSDK)/src/gpl-modules/include/
