ifeq ($(BCMSDK),)
ifneq ($(M),)
BCMSDK := $(M)
else
$(error BCMSDK must be set to the OpenNSA/src/gpl-modules tree)
endif
endif

obj-m := bcm-kernel-bde.o
bcm-kernel-bde-y := linux-kernel-bde.o
bcm-kernel-bde-y += linux_dma.o
bcm-kernel-bde-y += linux_shbde.o
bcm-kernel-bde-y += ../shared/mpool.o
bcm-kernel-bde-y += ../../shared/shbde_iproc.o
bcm-kernel-bde-y += ../../shared/shbde_mdio.o
bcm-kernel-bde-y += ../../shared/shbde_pci.o
bcm-kernel-bde-y += ../../../linux/kernel/modules/shared/gmodule.o
ccflags-y := -I$(BCMSDK)/systems/linux/kernel/modules/include/
ccflags-y += -I$(BCMSDK)/systems/bde/linux/include/
ccflags-y += -I$(BCMSDK)/systems/bde/shared/include/
ccflags-y += -I$(BCMSDK)/include/
