ifeq ($(BCMSDK),)
$(error BCMSDK must be set to the root of the OpenNSA source tree)
endif

obj-m := bcm-knet-mod.o
bcm-knet-mod-y := bcm-knet.o
bcm-knet-mod-y += ../../../../linux/kernel/modules/shared/gmodule.o
ccflags-y := -I$(BCMSDK)/src/gpl-modules/systems/linux/kernel/modules/include/
ccflags-y += -I$(BCMSDK)/src/gpl-modules/systems/bde/linux/include/
ccflags-y += -I$(BCMSDK)/src/gpl-modules/systems/bde/shared/include/
ccflags-y += -I$(BCMSDK)/src/gpl-modules/include/
