ifeq ($(BCMSDK),)
ifneq ($(M),)
BCMSDK := $(M)
else
$(error BCMSDK must be set to the OpenNSA/src/gpl-modules tree)
endif
endif

obj-m := bcm-knet-mod.o
bcm-knet-mod-y := bcm-knet.o
bcm-knet-mod-y += ../../../../linux/kernel/modules/shared/gmodule.o
ccflags-y := -I$(BCMSDK)/systems/linux/kernel/modules/include/
ccflags-y += -I$(BCMSDK)/systems/bde/linux/include/
ccflags-y += -I$(BCMSDK)/systems/bde/shared/include/
ccflags-y += -I$(BCMSDK)/include/
